### ISSUE TITLE
Cue sticks won't move on Oculus Quest

### ISSUE THREAD

**Issue by taeliouwolf** [Xiexe/VRCBilliards#1]
Upon testing in different worlds the cue sticks move fine in PCVR but doesn't seem to move on the Quest client. They are able to rotate but are stuck in place on the table.
![com vrchat oculus quest-20210126-134939](https://user-images.githubusercontent.com/78030475/106346987-d314f980-62b2-11eb-8835-14f86fd49d80.jpg)
![com vrchat oculus quest-20210126-134952](https://user-images.githubusercontent.com/78030475/106346988-d3ad9000-62b2-11eb-8036-6647b64da457.jpg)

**Comment by Terri00** [comment]
Likely fix: swap lines `229, 230` in cue script

https://github.com/Xiexe/VRCBilliards/blob/0a011e1ee4e0195d011c0dfbc4e85479b4b3ebe3/us/ht8b_cue.cs#L229-L230

**Comment by Xiexe** [comment]
Should be fixed on a local build -- Will be pushed after the weekend.
