### ISSUE TITLE
Buttons won't trigger if an avatar doesn't have finger bones rigged

### ISSUE THREAD

**Issue by taeliouwolf** [Xiexe/VRCBilliards#2]
Some avatars don't have finger bones rigged which causes the physical buttons on the table to not work at all. 
Maybe have a switch back to the usual trigger buttons if an avatar is detected to have no fingers rigged? sort of like how it works with this prefab https://bitbucket.org/akovaloid/vrc-physical-interaction/src/master/
![com vrchat oculus quest-20210130-041938](https://user-images.githubusercontent.com/78030475/106347027-31da7300-62b3-11eb-9915-b08096b01e8a.jpg)

**Comment by Xiexe** [comment]
Buttons will be reworked soon to use controller tracked position after I finish replacing the art assets to deal with licensing issues.

**Comment by Xiexe** [comment]
Should be fixed on a local build -- Will be pushed after the weekend.
