### ISSUE TITLE
Add artwork licensing note

### ISSUE THREAD

**Issue by Terri00** [Xiexe/VRCBilliards#3]
Hi, thanks for continuing project.
However there is some note that might need to be added about the 3d artwork with the project.

The unlicense **only** applies to the source code, and compiled binaries of this code, originally uploaded to the github page.

The asset package contains material which may catch people off guard because no license was included with the download ( The pool table itself has been released in the past under CC BY-NC-ND 3.0 )

Since the default copyright laws apply to artworks without a license (All Rights Reserved), I give permission to distribute them as if they were also CC BY-NC-ND 3.0

The only exception to the artwork licensing is my logo, which of course will remain as All Rights Reserved.

Further information at: https://docs.google.com/document/d/1xZODxDCFkgKbDJmGfzzJ0QEEDAaPcT0oNGCWBUXwjPg/edit#

**Comment by Xiexe** [comment]
As I forked the project under the unlicense, prior to your change, everything within the project is under the unlicense. As you said, they also apply to the binaries, which, in this case, includes the packaged assets.

As far as I understand: 
Licenses apply to anything and everything at that moment within the repository, and do not translate backwards. 

I.E. If I update a repository using MIT to GPL, code and assets forked prior to that remain under MIT.

That being said, if this is a problem for you, I'm more than happy to replace the assets with my own, and will work to do that over the course of a couple of days.

**Comment by Terri00** [comment]
please read the documwnt file linked above outlining how the Unlicense was never applied to the entire work, only source code

**Comment by Terri00** [comment]
It should be brought to attention that the recent license changes on my own github repository were added for _clarification purposes only and do not effect the content in the repository as there is no art there_. It wasn't until recently that I realized I still had exclusive rights to these artworks. 

The license changes were made to grant permission for distribution, taking them from ALL RIGHTS RESERVED to CC BY-NC-ND 3.0.

**Comment by Xiexe** [comment]
The art assets will be entirely replaced within the next two days. Once replaced, you will have nothing to be concerned about. I will not be updating the license in the meantime, as that means I will need to update it again in the next two days.

If you'd like to discuss this further, you have my contact information, feel free to contact me.

I will be closing this issue.

**Comment by Terri00** [comment]
Thank you for your cooperation.
