### ISSUE TITLE
Collider Pockets Need Updating

### ISSUE THREAD

**Issue by dragonash2019** [Xiexe/VRCBilliards#4]
Hi Xiexe,

Noticed you took this project over. I have Harry's latest version (1.5) and since he stopped supporting it, I started to fine tune it.
I noticed the collision for the pockets were way off and adjusted them to closely resemble what we actually "See" on the table itself (the collision was much wider, which made it look like the balls were going through the rails for impossible shots)
I've attached a screenshot of what the colliders look like now and we have noticed a big difference in accuracy (for the better)
Wanted to pass that along to you in case you weren't aware.

![Screenshot 2021-02-01 123637](https://user-images.githubusercontent.com/47508016/106495851-30af6e80-648a-11eb-9070-71a1057d1172.png)

**Comment by Xiexe** [comment]
Yeah, was aware! Collision meshes will be updated once I push the next build with the new art assets / sounds as well. :)

That should be happening hopefully tonight some time.

**Comment by Xiexe** [comment]
I'll also probably *try* to tweak the physics a little bit as I've been cleaning off my old pool table to record some foley, and I was going to study the physics a bit and adjust hit power and such to make it a little less arcadey in terms of how much power hits put in.

**Comment by dragonash2019** [comment]
Ok, since you seem to be on the same version, I'll post 2 separate things I found. BTW, do you have discord? I keep the pool table pretty "true" - aside from color updates and I know Harry had an issue with extensive mods. My friends and I play in our world regularly.

Not sure you want any additional pings, but willing to test/help if needed.

**Comment by Xiexe** [comment]
Yeah, Harry's issues wont apply with my updated assets, so you'll be free to do whatever you'd like once I'm done. 

I was also given full copyright permissions over the original assets through verbal agreement, but, I'd like to still replace everything out of moral. 

I do have Discord. Xiexe#0001

**Comment by Xiexe** [comment]
Changed in the upcoming update, closing issue!

**Comment by Terri00** [comment]
Just for reference on this, the collision is hard-coded and those colliders are only used as a kind of visual effect once you pocket something.

> I've attached a screenshot of what the colliders look like now and we have noticed a big difference in accuracy (for the better)

(this is impossible and can only be explained as a placebo)

Actual collider implementation is here:
https://github.com/Xiexe/VRCBilliards/blob/05ff60efe546d65cd31f0c8acf85dcb2577ee2b0/us/ht8b.cs#L1485

I've uploaded the geogebra sketch which i used to program this collision function. Is a little contrived, but may help to understand it if clarification is needed:
https://www.geogebra.org/m/urrgurnv
